## Write Python programs for
1. Representing sparse matrix 
2. Sparse matrix addition 
3. Sparse matrix transpose

In [1]:
import numpy as np

In [2]:
from scipy.sparse import csr_matrix

**Representing a matrix using NumPy**

In [3]:
A = np.matrix([[1, 0, 0, 0], [0, 2, 0, 0], [0, 0, 3, 0], [0, 0, 0, 4]])

In [4]:
print(A)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


**1. Program to represent a sparse matrix.**

In [5]:
csr_matrix((3, 4), dtype = np.int8).toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [10]:
sparse = csr_matrix(A)
print("Sparse Matrix:")
print(sparse)

Sparse Matrix:
  (0, 0)	1
  (1, 1)	2
  (2, 2)	3
  (3, 3)	4


In [17]:
row1 = np.array([0, 0, 1, 2, 2])
col1 = np.array([0, 2, 2, 0, 2])
data1 = np.array([1, 2, 3, 4, 5])
sparse_matrix1 = csr_matrix((data1, (row1, col1)), shape = (3, 3)).toarray()

In [18]:
# print sparse_matrix_repr
print("Sparse Matrix:")
print(sparse_matrix_repr)

Sparse Matrix:
[[1 0 2]
 [0 0 3]
 [4 0 5]]


**2. Program to add two sparse matrices.**

In [19]:
row2 = np.array([0, 1, 1])
col2 = np.array([2, 0, 1])
data2 = np.array([9, 8, 1])
sparse_matrix2 = csr_matrix((data2, (row2, col2)), shape = (3, 3)).toarray()
sparse_add = sparse_matrix1 + sparse_matrix2
print("Addition of sparse_matrix1 and sparse_matrix2:")
print(sparse_add)

Addition of sparse_matrix1 and sparse_matrix2:
[[ 1  0 11]
 [ 8  1  3]
 [ 4  0  5]]


**3. Program to transpose a sparse matrix.**

In [20]:
row3 = np.array([0, 1, 1, 2, 2])
col3 = np.array([2, 0, 1, 1, 2])
data3 = np.array([9, 8, 1, 9, 3])
sparse_original = csr_matrix((data3, (row3, col3)), shape = (3, 3)).toarray()
print("Original Sparse Matrix is:")
print(sparse_original)
sparse_transpose = csr_matrix((data3, (col3, row3)), shape = (3, 3)).toarray()
print("Transposed Sparse Matrix is:")
print(sparse_transpose)

Original Sparse Matrix is:
[[0 0 9]
 [8 1 0]
 [0 9 3]]
Transposed Sparse Matrix is:
[[0 8 0]
 [0 1 9]
 [9 0 3]]
